//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImplementacionCU92.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Escuela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Escuela()
        {
            this.ReservaVisita = new HashSet<ReservaVisita>();
        }
    
        public int id_escuela { get; set; }
        public string domicilio { get; set; }
        public string mail { get; set; }
        public string nombre { get; set; }
        public string telefCelular { get; set; }
        public string telefFijo { get; set; }


        public string[] mostrarNombres()
        {
            using (Entidades db = new Entidades())
            {
                IList<Escuela> esc = db.Escuela.ToList<Escuela>();
                string[] nombres = new string[esc.Count()];       
                for(int i = 0; i <= esc.Count() -1; i++)
                {
                    nombres[i] = esc[i].nombre;
                }
                return nombres;
            }

        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaVisita> ReservaVisita { get; set; }
    }
}
