//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImplementacionCU92.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioEmpleado
    {
        public Nullable<int> id_empleado { get; set; }
        public int id_horaEmpleado { get; set; }
        public Nullable<System.TimeSpan> horaIngreso { get; set; }
        public Nullable<System.TimeSpan> horaSalida { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
