//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImplementacionCU92.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obra()
        {
            this.DetalleExposicion = new HashSet<DetalleExposicion>();
        }
    
        public Nullable<double> alto { get; set; }
        public Nullable<double> ancho { get; set; }
        public string codigoSensor { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.TimeSpan> duracionExtendida { get; set; }
        public Nullable<System.TimeSpan> duracionResumida { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaPrimerIngreso { get; set; }
        public string nombreObra { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> valuacion { get; set; }
        public int id_obra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleExposicion> DetalleExposicion { get; set; }
    }
}
