//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImplementacionCU92.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Sede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sede()
        {
            this.Exposicion = new HashSet<Exposicion>();
        }
    
        public int id_sede { get; set; }
        public Nullable<int> cantMaxVisitantes { get; set; }
        public Nullable<int> cantMaxPorGuia { get; set; }
        public string nombre { get; set; }

        public string[] mostrarNombres()
        {
            using (Entidades db = new Entidades())
            {
                IList<Sede> sede = db.Sede.ToList<Sede>();
                string[] nombres = new string[sede.Count()];       
                for(int i = 0; i <= sede.Count() -1; i++)
                {
                    nombres[i] = sede[i].nombre;
                }
                return nombres;
            }

        }


    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exposicion> Exposicion { get; set; }
    }
}
