//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImplementacionCU92.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TipoVisita
    {
        public string nombre { get; set; }
        public int id_tipoVisita { get; set; }


        public string[] mostrarNombres()
        {
            using (Entidades db = new Entidades())
            {
                IList<TipoVisita> tipoVisita = db.TipoVisita.ToList<TipoVisita>();
                string[] nombres = new string[tipoVisita.Count()];
                for (int i = 0; i <= tipoVisita.Count() - 1; i++)
                {
                    nombres[i] = tipoVisita[i].nombre;
                }
                return nombres;
            }

        }
    }
}
